steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['-']
    args: [
      'functions', 'deploy', 'interface_opensource',
      '--trigger-http',
      '--allow-unauthenticated',
      '--entry-point', 'interface',
      '--runtime', 'python37',
      '--region', 'europe-west1',
      '--source', 'interface',
      '--update-labels', 'project=models,environment=production'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['-']
    args: [
      'functions', 'deploy', 'document_preprocessing_opensource',
      '--trigger-topic', 'document_preprocessing_opensource',
      '--entry-point', 'detect_text',
      '--runtime', 'python37',
      '--region', 'europe-west1',
      '--source', 'document_preprocessing',
      '--update-labels', 'project=models,environment=production'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['-']
    args: [
      'functions', 'deploy', 'google_ocr_opensource',
      '--trigger-topic', 'google_ocr_opensource',
      '--entry-point', 'detect_text',
      '--runtime', 'python37',
      '--region', 'europe-west1',
      '--source', 'google_ocr',
      '--update-labels', 'project=models,environment=production'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['-']
    args: [
      'functions', 'deploy', 'document_postprocessing_opensource',
      '--trigger-topic', 'document_postprocessing_opensource',
      '--entry-point', 'extract_data',
      '--runtime', 'python37',
      '--region', 'europe-west1',
      '--source', 'document_preprocessing',
      '--update-labels', 'project=models,environment=production'
    ]
